stack:
  nginx:
    document_root: web
    index: app.php

  php:
    version: 5.6

deployment:
  install:
    - composer install --prefer-dist --no-interaction --optimize-autoloader
    - chown -R www-data:www-data app/cache/ app/logs/
